import { Inter } from "next/font/google";
import "../globals.css";
import Searchbar from "@/components/searchbar/searchbar";
import Sidebar from "@/components/sidebar/sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className + "flex flex-col h-[100vh]"}>
                <Searchbar />
                <div className="flex flex-row">
                    <Sidebar />
                    {children}
                </div>
            </body>
        </html>
    );
}
