import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/toaster";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
    title: "Okit",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className + "flex flex-col h-[100vh]"}>
                {children}
                <Toaster />
            </body>
        </html>
    );
}
